sudo: required
language: go

env:
  - REPO=otobrglez/o7tracker
  - GO_GAE_SDK_VERSION=1.9.35

before_install:
  - wget -q -O "/tmp/appengine.zip" https://storage.googleapis.com/appengine-sdks/featured/go_appengine_sdk_linux_amd64-$GO_GAE_SDK_VERSION.zip
  - unzip -q -d "${HOME}" "/tmp/appengine.zip"
  - cd "${HOME}/go_appengine"
  - export GAE=$(pwd)
  - popd

install:
  - cd "$TRAVIS_BUILD_DIR"
  - export GOROOT=$GAE/goroot
  - export PATH=$GAE:$PATH
  - goapp version

script:
  - goapp get -d -v ./goapp




