runtime: go
api_version: go1

env_variables:
  FALLBACK_URL: 'http://outfit7.com'
  AUTH_USER: 'admin'
  AUTH_PASSWORD: 'admin'

handlers:
  - url: /.*
    script: _go_app

  - url: /tasks/update_stats
    script: _go_app
    login: admin

skip_files:
  - ^(.*/)?\..*
